// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/** Align with `src/lib/env.ts` (Vercel Marketplace Supabase). */
function prismaDatasourceUrl(): string | undefined {
  return (
    process.env["DIRECT_URL"] ||
    process.env["POSTGRES_URL_NON_POOLING"] ||
    process.env["DATABASE_URL"] ||
    process.env["POSTGRES_PRISMA_URL"] ||
    process.env["POSTGRES_URL"] ||
    undefined
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: prismaDatasourceUrl(),
  },
});
