// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/**
 * Align with `src/lib/env.ts`. Production is on Google Cloud SQL
 * (asia-southeast1) since 2026-05-03; only `DIRECT_URL` (CLI override
 * for migrations) and `DATABASE_URL` are honored.
 */
function prismaDatasourceUrl(): string | undefined {
  return process.env["DIRECT_URL"] || process.env["DATABASE_URL"] || undefined;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: prismaDatasourceUrl(),
  },
});
